blank_issues_enabled: true
contact_links:
  - name: I want help using Migaloo
    url: https://discordapp.com/channels/908044702794801233/987301947440767006
    about: Ask any questions related to using or integrating with Migaloo, deploying your decentralized applications and so on.
