name: Verify Statesync

on: [push, pull_request]

jobs:
  verify_statesync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up shell
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run verify.sh script
        run: |
          chmod +x ./statesync.bash
          bash scripts/statesync.bash

      - name: Check script with ShellCheck
        run: |
          shellcheck ./statesync.bash
